updates to version 0.6

diff --git a/.github/workflows/pypi.yaml b/.github/workflows/pypi.yaml
--- a/.github/workflows/pypi.yaml
+++ b/.github/workflows/pypi.yaml
@@ -19,6 +19,7 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
+        lfs: true
         python-version: "3.7"
     - name: Install pypa/build
       run: >-
@@ -42,97 +43,97 @@ jobs:
       if: steps.store_distribution_packages.outcome == 'failure'
       run: exit 1
 
-  publish-to-testpypi:
-    name: Publish Python 🐍 distribution 📦 to TestPyPI
-    needs:
-    - build
-    runs-on: ubuntu-latest
+#   publish-to-testpypi:
+#     name: Publish Python 🐍 distribution 📦 to TestPyPI
+#     needs:
+#     - build
+#     runs-on: ubuntu-latest
 
-    environment:
-      name: testpypi
-      url: https://test.pypi.org/p/quotes-library
+#     environment:
+#       name: testpypi
+#       url: https://test.pypi.org/p/quotes-library
 
-    permissions:
-      id-token: write  # IMPORTANT: mandatory for trusted publishing
+#     permissions:
+#       id-token: write  # IMPORTANT: mandatory for trusted publishing
 
-    steps:
-    - name: Download all the dists
-      uses: actions/download-artifact@v4
-      with:
-        name: python-package-distributions
-        path: dist/
-    - name: Publish distribution 📦 to TestPyPI
-      id: publish_to_test_pypi
-      uses: pypa/gh-action-pypi-publish@release/v1
-      with:
-        repository-url: https://test.pypi.org/legacy/
-    - name: Test PYPI Upload and Download status
-      if: steps.publish_to_test_pypi.outcome == 'failure'
-      run: exit 1
+#     steps:
+#     - name: Download all the dists
+#       uses: actions/download-artifact@v4
+#       with:
+#         name: python-package-distributions
+#         path: dist/
+#     - name: Publish distribution 📦 to TestPyPI
+#       id: publish_to_test_pypi
+#       uses: pypa/gh-action-pypi-publish@release/v1
+#       with:
+#         repository-url: https://test.pypi.org/legacy/
+#     - name: Test PYPI Upload and Download status
+#       if: steps.publish_to_test_pypi.outcome == 'failure'
+#       run: exit 1
 
-  publish-to-pypi:
-    name: >-
-      Publish Python 🐍 distribution 📦 to PyPI
-    if: github.ref == 'refs/heads/production' && github.event_name == 'push'  # only publish to PyPI on tag pushes
-    needs:
-    - build
-    runs-on: ubuntu-latest
-    environment:
-      name: pypi
-      url: https://pypi.org/p/quotes-library  # Replace <package-name> with your PyPI project name
-    permissions:
-      id-token: write  # IMPORTANT: mandatory for trusted publishing
+#   publish-to-pypi:
+#     name: >-
+#       Publish Python 🐍 distribution 📦 to PyPI
+#     if: github.ref == 'refs/heads/production' && github.event_name == 'push'  # only publish to PyPI on tag pushes
+#     needs:
+#     - build
+#     runs-on: ubuntu-latest
+#     environment:
+#       name: pypi
+#       url: https://pypi.org/p/quotes-library  # Replace <package-name> with your PyPI project name
+#     permissions:
+#       id-token: write  # IMPORTANT: mandatory for trusted publishing
 
-    steps:
-    - name: Download all the dists
-      uses: actions/download-artifact@v4
-      with:
-        name: python-package-distributions
-        path: dist/
-    - name: Publish distribution 📦 to PyPI
-      uses: pypa/gh-action-pypi-publish@release/v1
+#     steps:
+#     - name: Download all the dists
+#       uses: actions/download-artifact@v4
+#       with:
+#         name: python-package-distributions
+#         path: dist/
+#     - name: Publish distribution 📦 to PyPI
+#       uses: pypa/gh-action-pypi-publish@release/v1
 
-  github-release:
-    name: >-
-      Sign the Python 🐍 distribution 📦 with Sigstore
-      and upload them to GitHub Release
-    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
-    needs:
-    - publish-to-pypi
-    runs-on: ubuntu-latest
+#   github-release:
+#     name: >-
+#       Sign the Python 🐍 distribution 📦 with Sigstore
+#       and upload them to GitHub Release
+#     if: github.ref == 'refs/heads/production' && github.event_name == 'push'
+#     needs:
+#     - publish-to-pypi
+#     runs-on: ubuntu-latest
 
-    permissions:
-      contents: write  # IMPORTANT: mandatory for making GitHub Releases
-      id-token: write  # IMPORTANT: mandatory for sigstore
+#     permissions:
+#       contents: write  # IMPORTANT: mandatory for making GitHub Releases
+#       id-token: write  # IMPORTANT: mandatory for sigstore
 
-    steps:
-    - name: Download all the dists
-      uses: actions/download-artifact@v4
-      with:
-        name: python-package-distributions
-        path: dist/
-    - name: Sign the dists with Sigstore
-      uses: sigstore/gh-action-sigstore-python@v2.1.1
-      with:
-        inputs: >-
-          ./dist/*.tar.gz
-          ./dist/*.whl
-    - name: Create GitHub Release
-      env:
-        GITHUB_TOKEN: ${{ github.token }}
-      run: >-
-        gh release create
-        '${{ github.ref_name }}'
-        --repo '${{ github.repository }}'
-        --notes ""
-    - name: Upload artifact signatures to GitHub Release
-      env:
-        GITHUB_TOKEN: ${{ github.token }}
-      # Upload to GitHub Release using the `gh` CLI.
-      # `dist/` contains the built packages, and the
-      # sigstore-produced signatures and certificates.
-      run: >-
-        gh release upload
-        '${{ github.ref_name }}' dist/**
-        --repo '${{ github.repository }}'
+#     steps:
+#     - name: Download all the dists
+#       uses: actions/download-artifact@v4
+#       with:
+#         name: python-package-distributions
+#         path: dist/
+#     - name: Sign the dists with Sigstore
+#       uses: sigstore/gh-action-sigstore-python@v2.1.1
+#       with:
+#         inputs: >-
+#           ./dist/*.tar.gz
+#           ./dist/*.whl
+#     - name: Create GitHub Release
+#       env:
+#         GITHUB_TOKEN: ${{ github.token }}
+#       run: >-
+#         gh release create
+#         '${{ github.ref_name }}'
+#         --repo '${{ github.repository }}'
+#         --notes ""
+#     - name: Upload artifact signatures to GitHub Release
+#       env:
+#         GITHUB_TOKEN: ${{ github.token }}
+#       # Upload to GitHub Release using the `gh` CLI.
+#       # `dist/` contains the built packages, and the
+#       # sigstore-produced signatures and certificates.
+#       run: >-
+#         gh release upload
+#         '${{ github.ref_name }}' dist/**
+#         --repo '${{ github.repository }}'
 
